---
- hosts: all
  tasks:

    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600
      sudo: yes

    - name: upgrade linux kernel to 3.8 (docker recommended)
      apt: pkg=linux-image-generic-lts-raring
      sudo: yes
      with_items:
        - linux-headers-generic-lts-raring
      notify: 
        - Restart vm

    ## Commented out because buildroot is not available via apt.
    ## TODO: find an alternative method for installing buildroot.
    # - name: ensure buildroot is installed
    #   apt: pkg=buildroot=2013.08.1 state=present
    #   sudo: yes

    - name: ensure docker is installed
      apt: pkg=docker state=latest
      sudo: yes

  handlers:
    - name: Restart vm
      command: /sbin/reboot
      sudo: yes

